/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.lexer.kotlin;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/lexer/kotlin")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class KotlinLexerTestGenerated extends AbstractKotlinLexerTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
    }

    public void testAllFilesPresentInKotlin() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/lexer/kotlin"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("compiler/testData/lexer/kotlin/whitescapeCharacters")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class WhitescapeCharacters extends AbstractKotlinLexerTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
        }

        public void testAllFilesPresentInWhitescapeCharacters() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/lexer/kotlin/whitescapeCharacters"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("compiler/testData/lexer/kotlin/whitescapeCharacters/carrageReturn")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class CarrageReturn extends AbstractKotlinLexerTest {
            private void runTest(String testDataFilePath) throws Exception {
                KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
            }

            public void testAllFilesPresentInCarrageReturn() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/lexer/kotlin/whitescapeCharacters/carrageReturn"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("carrageReturn.kt")
            public void testCarrageReturn() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/carrageReturn/carrageReturn.kt");
            }

            @TestMetadata("carrageReturnInComments.kt")
            public void testCarrageReturnInComments() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/carrageReturn/carrageReturnInComments.kt");
            }

            @TestMetadata("carrageReturnInStringLiterals.kt")
            public void testCarrageReturnInStringLiterals() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/carrageReturn/carrageReturnInStringLiterals.kt");
            }
        }

        @TestMetadata("compiler/testData/lexer/kotlin/whitescapeCharacters/lineSeparator")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class LineSeparator extends AbstractKotlinLexerTest {
            private void runTest(String testDataFilePath) throws Exception {
                KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
            }

            public void testAllFilesPresentInLineSeparator() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/lexer/kotlin/whitescapeCharacters/lineSeparator"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("lineSeparator.kt")
            public void testLineSeparator() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/lineSeparator/lineSeparator.kt");
            }

            @TestMetadata("lineSeparatorInComments.kt")
            public void testLineSeparatorInComments() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/lineSeparator/lineSeparatorInComments.kt");
            }

            @TestMetadata("lineSeparatorInStringLiterals.kt")
            public void testLineSeparatorInStringLiterals() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/lineSeparator/lineSeparatorInStringLiterals.kt");
            }
        }

        @TestMetadata("compiler/testData/lexer/kotlin/whitescapeCharacters/nextLine")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class NextLine extends AbstractKotlinLexerTest {
            private void runTest(String testDataFilePath) throws Exception {
                KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
            }

            public void testAllFilesPresentInNextLine() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/lexer/kotlin/whitescapeCharacters/nextLine"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("nextLine.kt")
            public void testNextLine() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/nextLine/nextLine.kt");
            }

            @TestMetadata("nextLineInComments.kt")
            public void testNextLineInComments() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/nextLine/nextLineInComments.kt");
            }

            @TestMetadata("nextLineInStringLiterals.kt")
            public void testNextLineInStringLiterals() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/nextLine/nextLineInStringLiterals.kt");
            }
        }

        @TestMetadata("compiler/testData/lexer/kotlin/whitescapeCharacters/pageBreak")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class PageBreak extends AbstractKotlinLexerTest {
            private void runTest(String testDataFilePath) throws Exception {
                KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
            }

            public void testAllFilesPresentInPageBreak() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/lexer/kotlin/whitescapeCharacters/pageBreak"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("pageBreak.kt")
            public void testPageBreak() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/pageBreak/pageBreak.kt");
            }

            @TestMetadata("pageBreakInComments.kt")
            public void testPageBreakInComments() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/pageBreak/pageBreakInComments.kt");
            }

            @TestMetadata("pageBreakInStringLiterals.kt")
            public void testPageBreakInStringLiterals() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/pageBreak/pageBreakInStringLiterals.kt");
            }
        }

        @TestMetadata("compiler/testData/lexer/kotlin/whitescapeCharacters/paragraphSeparator")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class ParagraphSeparator extends AbstractKotlinLexerTest {
            private void runTest(String testDataFilePath) throws Exception {
                KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
            }

            public void testAllFilesPresentInParagraphSeparator() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/lexer/kotlin/whitescapeCharacters/paragraphSeparator"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("paragraphSeparator.kt")
            public void testParagraphSeparator() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/paragraphSeparator/paragraphSeparator.kt");
            }

            @TestMetadata("paragraphSeparatorInComments.kt")
            public void testParagraphSeparatorInComments() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/paragraphSeparator/paragraphSeparatorInComments.kt");
            }

            @TestMetadata("paragraphSeparatorInStringLiterals.kt")
            public void testParagraphSeparatorInStringLiterals() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/paragraphSeparator/paragraphSeparatorInStringLiterals.kt");
            }
        }

        @TestMetadata("compiler/testData/lexer/kotlin/whitescapeCharacters/verticalTab")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class VerticalTab extends AbstractKotlinLexerTest {
            private void runTest(String testDataFilePath) throws Exception {
                KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
            }

            public void testAllFilesPresentInVerticalTab() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/lexer/kotlin/whitescapeCharacters/verticalTab"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("verticalTab.kt")
            public void testVerticalTab() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/verticalTab/verticalTab.kt");
            }

            @TestMetadata("verticalTabInComments.kt")
            public void testVerticalTabInComments() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/verticalTab/verticalTabInComments.kt");
            }

            @TestMetadata("verticalTabInStringLiterals.kt")
            public void testVerticalTabInStringLiterals() throws Exception {
                runTest("compiler/testData/lexer/kotlin/whitescapeCharacters/verticalTab/verticalTabInStringLiterals.kt");
            }
        }
    }
}
